name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Set initial check
        conclusion: ${{ job.status }}
        
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # name: Build with Gradle
    #  run: ./gradlew build
    
    # Execute unit tests
    #- name: Unit Test
    #  run: ./gradlew testDebugUnitTest
      
    # Execut Intrumented tests
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 27
        profile: pixel_4a
        script: ./gradlew connectedCheck
        
    - name: Android Test Report Action
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
      
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Set checks
        conclusion: ${{ job.status }}
