name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # Execute unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
      
    - name: Android Test Report Action
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }}
        
        
  instrumented_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew


    # Execut Intrumented tests
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 27
        profile: pixel_4a
        script: ./gradlew connectedCheck
        
    - name: Android Test Report Action
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
      
